services:
    catering-app:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
                WWWUSER: '1000'
        image: 'catering-app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
#            - redis
    pgsql:
        image: 'postgres:latest'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: 'password'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'sail-redis:/data'
#        networks:
#            - sail
#        healthcheck:
#            test:
#                - CMD
#                - redis-cli
#                - ping
#            retries: 3
#            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
